# Generated by Django 5.1.6 on 2025-02-19 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0002_remove_course_code_alter_course_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='lecturer',
            name='unavailable',
        ),
        migrations.AlterField(
            model_name='classroom',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='course',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='day',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='start_time',
            field=models.IntegerField(),
        ),
    ]
