# Generated by Django 5.1.6 on 2025-02-19 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0003_remove_classroom_capacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='unavailable',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
